### ISSUE TITLE
Terry's Welsh Bar is actually an Indian take away

### ISSUE THREAD

**Issue by mezpahlan** [nihp-public/covid-19-app-android-ag-public#16]
**Describe the bug**
The text underneath the example QR code in the [Welsh version of QR code help poster](https://github.com/nhsx/covid-19-app-android-ag-public/blob/master/app/src/main/res/drawable-nodpi/qr_code_help_poster_welsh.png) should _probably_ be blurred in the same way that the text in the [English version](https://github.com/nhsx/covid-19-app-android-ag-public/blob/master/app/src/main/res/drawable-nodpi/qr_code_help_poster.png) is blurred.

At the very least the good people of Briton Ferry deserve to have an accurate representation of their high street. The location is currently occupied by a fine Indian takeaway. With a pretty decent menu and prices from what I can see :yum: .

**To Reproduce**
1. Open [Welsh version of QR code help poster](https://github.com/nhsx/covid-19-app-android-ag-public/blob/master/app/src/main/res/drawable-nodpi/qr_code_help_poster_welsh.png).
2. Observe example venue location below the QR code.

**Expected behavior**
Example venue location should either be blurred or completely made up / non-existent.

**Screenshots**
See [Welsh version of QR code help poster](https://github.com/nhsx/covid-19-app-android-ag-public/blob/master/app/src/main/res/drawable-nodpi/qr_code_help_poster_welsh.png).

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Obviously..... obviously..... this is very low priority :smile_cat: .

**Comment by osianSmith** [comment]
I've tried to scan the QR code in the NHS app and it seems to be an inaccurate QR code so I guess this isn't really a problem? Maybe its a reference [to this?](https://www.bbc.co.uk/news/business-46748193)

**Comment by nhs-covid19** [comment]
Example images within the app have been modified, so closing this issue.
