### ISSUE TITLE
Dagger injection for Activities should happen before super.

### ISSUE THREAD

**Issue by mezpahlan** [nihp-public/covid-19-app-android-ag-public#18]
**Describe the bug**
According to the Dagger documentation [injection in Activities should happen _before_ the call to `super.onCreate()`](https://dagger.dev/dev-guide/android#when-to-inject). In most (all?) of the Activities in the project injection is done after the call to `super.onCreate()`.

**To Reproduce**
Open any Activity in the project.

**Expected behavior**
Dagger injection for Activities follows guidance from Dagger project and is done before any call to `super.onCreate()`.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

1. I don't think this is a massive issue by the way. It's just not according to the Dagger docs.

1. I haven't found any Fragments yet but the injection call should be in `onAttach` before the call to `super` unless you've hooked up a FragmentFactory that allows for constructor injection :smile_cat: .

**Comment by nhs-covid19** [comment]
Closing this issue as we have not had any problems relating to dependency injection within the app
